/* tslint:disable */
/**
 * This is an autogenerated file created by the Stencil compiler.
 * It contains typing information for all components that exist in this project.
 */


import { HTMLStencilElement, JSXBase } from '@stencil/core/internal';


export namespace Components {
  interface CardItem {
    'classNames': string;
  }
  interface FlipDiv {
    'height': string;
    'width': string;
  }
}

declare global {


  interface HTMLCardItemElement extends Components.CardItem, HTMLStencilElement {}
  var HTMLCardItemElement: {
    prototype: HTMLCardItemElement;
    new (): HTMLCardItemElement;
  };

  interface HTMLFlipDivElement extends Components.FlipDiv, HTMLStencilElement {}
  var HTMLFlipDivElement: {
    prototype: HTMLFlipDivElement;
    new (): HTMLFlipDivElement;
  };
  interface HTMLElementTagNameMap {
    'card-item': HTMLCardItemElement;
    'flip-div': HTMLFlipDivElement;
  }
}

declare namespace LocalJSX {
  interface CardItem extends JSXBase.HTMLAttributes<HTMLCardItemElement> {
    'classNames'?: string;
  }
  interface FlipDiv extends JSXBase.HTMLAttributes<HTMLFlipDivElement> {
    'height'?: string;
    'onClicked'?: (event: CustomEvent<any>) => void;
    'width'?: string;
  }

  interface IntrinsicElements {
    'card-item': CardItem;
    'flip-div': FlipDiv;
  }
}

export { LocalJSX as JSX };


declare module "@stencil/core" {
  export namespace JSX {
    interface IntrinsicElements extends LocalJSX.IntrinsicElements {}
  }
}


